(function(x,p,n,f,v,V){function w(b){return!isNaN(parseFloat(b))&&isFinite(b)}function D(b){return(new RegExp(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i)).test(b)}function H(b){return(new RegExp(/^[0-9a-f]{32}$/i)).test(b)}function I(b,d,c){b=b||[];var a=this,f=Math.floor((new Date).getTime()/1E3);a._session={rtgsession_ts_creation_cookie:b[0],rtgsession_ttl:b[1],rtgsession_seq:b[2],rtgsession_id_prev:b[3],rtgsession_id:b[4],rtgsession_ts:b[5],rtgsession_hits:b[6]};a.setUpNewSession=
function(){a._session.rtgsession_id=d+":"+f;a._session.rtgsession_ts=f;a._session.rtgsession_hits=1};a.setUpNewSessionHeader=function(){a._session.rtgsession_ts_creation_cookie=f;a._session.rtgsession_ttl=c;a._session.rtgsession_seq=1;a._session.rtgsession_id_prev=""};a.getValue=function(){return a._session.rtgsession_ts_creation_cookie+"_"+a._session.rtgsession_ttl+"_"+a._session.rtgsession_seq+"_"+a._session.rtgsession_id_prev+"_"+a._session.rtgsession_id+"_"+a._session.rtgsession_ts+"_"+a._session.rtgsession_hits};
a.getEncodedValue=function(){return encodeURIComponent(a.getValue())};a.createNew=function(){a.setUpNewSessionHeader();a.setUpNewSession()};a.checkError=function(){function b(a,b){c.isValid=!1;c.msg+=c.msg?"|"+a:a}function d(a){if(a&&(a=a.split(":"),a.length&&2===a.length))return D(a[0])&&w(a[1])}var c={isValid:!0,msg:""};try{w(a._session.rtgsession_ts_creation_cookie)?a._session.rtgsession_ts_creation_cookie=parseFloat(a._session.rtgsession_ts_creation_cookie):b("rtgsession_ts_creation_cookie"),
w(a._session.rtgsession_ttl)?a._session.rtgsession_ttl=parseFloat(a._session.rtgsession_ttl):b("rtgsession_ttl"),w(a._session.rtgsession_seq)?a._session.rtgsession_seq=parseFloat(a._session.rtgsession_seq):b("rtgsession_seq"),a._session.rtgsession_id_prev&&!d(a._session.rtgsession_id_prev)?b("rtgsession_id_prev"):(a._session.rtgsession_id_prev_uid=a._session.rtgsession_id_prev.split(":")[0],a._session.rtgsession_id_prev_ts=parseFloat(a._session.rtgsession_id_prev.split(":")[1])),a._session.rtgsession_id&&
!d(a._session.rtgsession_id)?b("rtgsession_id"):(a._session.rtgsession_id_uid=a._session.rtgsession_id.split(":")[0],a._session.rtgsession_id_ts=parseFloat(a._session.rtgsession_id.split(":")[1])),w(a._session.rtgsession_ts)?a._session.rtgsession_ts=parseFloat(a._session.rtgsession_ts):b("rtgsession_ts"),f<parseFloat(a._session.rtgsession_ts)&&b("rtgsession_duration"),w(a._session.rtgsession_hits)||b("rtgsession_hits")}catch(J){k(c.msg+"+checkError+function+failed&trossion="+a.getEncodedValue()+"&timestamp="+
a.timeStamp,17)}return c};a.updateWithNewSession=function(){a._session.rtgsession_seq=parseFloat(a._session.rtgsession_seq)+1;a._session.rtgsession_id_prev=a._session.rtgsession_id;a.setUpNewSession()};a.updateSession=function(){a._session.rtgsession_ts=f;a._session.rtgsession_hits=parseFloat(a._session.rtgsession_hits)+1};a.updateEv=function(b){b=b||{};b.rtgsession_ts_creation_cookie=a._session.rtgsession_ts_creation_cookie;b.rtgsession_ttl=a._session.rtgsession_ttl;b.rtgsession_seq=a._session.rtgsession_seq;
b.rtgsession_id_prev=a._session.rtgsession_id_prev;b.rtgsession_id_prev_uid=a._session.rtgsession_id_prev_uid;b.rtgsession_id_prev_ts=a._session.rtgsession_id_prev_ts;b.rtgsession_id=a._session.rtgsession_id;b.rtgsession_id_uid=a._session.rtgsession_id_uid;b.rtgsession_id_ts=a._session.rtgsession_id_ts;b.rtgsession_ts=a._session.rtgsession_ts;b.rtgsession_hits=a._session.rtgsession_hits;b.rtgsession_duration=a._session.rtgsession_duration;b.rtgsession_seq_duration=a._session.rtgsession_seq_duration;
return b};a.getSessionForTagContainer=function(){return[["rtgsession_ts_creation_cookie",[a._session.rtgsession_ts_creation_cookie]],["rtgsession_ttl",[a._session.rtgsession_ttl]],["rtgsession_seq",[a._session.rtgsession_seq]],["rtgsession_id_prev",[a._session.rtgsession_id_prev]],["rtgsession_id_prev_uid",[a._session.rtgsession_id_prev_uid]],["rtgsession_id_prev_ts",[a._session.rtgsession_id_prev_ts]],["rtgsession_id",[a._session.rtgsession_id]],["rtgsession_id_uid",[a._session.rtgsession_id_uid]],
["rtgsession_id_ts",[a._session.rtgsession_id_ts]],["rtgsession_ts",[a._session.rtgsession_ts]],["rtgsession_hits",[a._session.rtgsession_hits]],["rtgsession_duration",[a._session.rtgsession_duration]],["rtgsession_seq_duration",[a._session.rtgsession_seq_duration]]]};(function(a){if(7>b.length)a.createNew();else{var d=a.checkError();d.isValid?f-parseFloat(a._session.rtgsession_ts)>c?a.updateWithNewSession():a.updateSession():(k(d.msg+"&trossion="+a.getEncodedValue()+"&timestamp="+a.timeStamp,17),
a.createNew())}a._session.rtgsession_id_ts&&a._session.rtgsession_ts&&(a._session.rtgsession_duration=a._session.rtgsession_ts-parseFloat(a._session.rtgsession_id_ts));a._session.rtgsession_id_ts&&a._session.rtgsession_id_prev_ts&&(a._session.rtgsession_seq_duration=a._session.rtgsession_ts-a._session.rtgsession_id_prev_ts)})(a);return a}function L(b,d){function c(){return[{id:"default",version:1,ttl:30,events:[{coef:-.1071305787347127},{coef:.216131896556964,cond:"rtgsession_seq"},{coef:1.2656065071142095E-4,
cond:"rtgsession_duration"},{coef:.07467899685829335,cond:"rtgsession_hits"}]}]}function a(a){try{return c().map(function(b){return l(b,a)})}catch(q){return k(q+"createNewScore: return score empty",20),c()}}function m(a,b){try{var d=parseFloat(a.value),c=parseFloat(a.lower_bound_value),f=parseFloat(a.upper_bound_value),q=parseFloat(b[a.key]);switch(a.operator){case "BETWEEN":return q>c&&q<f;case "==":return b[a.key]===a.value;case "<=":return q<=d;case ">=":return q>=d;case ">":return q>d;case "<":return q<
d;case "AND":return a.valueA&&a.valueB;case "OR":return a.valueA||a.valueB;case "IS NOT NULL":return b.hasOwnProperty(a.key)&&""!==b[a.key]&&void 0!==b[a.key];case "NOT":return!a.value;case "REGEXP":return(new RegExp(a.value,"giu")).test(b[a.key]);default:k(e+error.msg+"+operator not supported for visitor scoring",20)}}catch(F){k(F+"evaluateExpression",20)}}function g(a){try{var b=[];if("string"===typeof a&&0<a.length)for(var d=a.split(" ");d&&0<d.length;){var c=d.shift();if('"'===c[0]){if('"'!==
c[c.length-1])for(;;){var f=d.shift();if(void 0===f){c=void 0;break}c=c+" "+f;if('"'===f[f.length-1])break}void 0!==c&&(c=c.substring(1,c.length-1))}"IS"==c&&"NULL"===d[0]&&(c=c+" "+d.shift());"IS"==c&&"NOT"===d[0]&&"NULL"===d[1]&&(c=c+" "+d.shift()+" "+d.shift());void 0!==c&&b.push(c)}return b}catch(X){k(X+"lexer",20)}return[]}function r(a,b){var c=[];try{g(a).forEach(function(a){var d={operator:a};switch(a){case "BETWEEN":d.upper_bound_value=c.pop();d.lower_bound_value=c.pop();d.key=c.pop();a=m(d,
b);break;case "==":case "<=":case ">=":case ">":case "<":case "REGEXP":d.value=c.pop();d.key=c.pop();a=m(d,b);break;case "AND":case "OR":d.valueB=c.pop();d.valueA=c.pop();a=m(d,b);break;case "NOT":d.value=c.pop();a=m(d,b);break;case "IS NOT NULL":d.key=c.pop();a=m(d,b);break;case "!=":d.value=c.pop();d.key=c.pop();a=r(d.key+" "+d.value+" == NOT",b);break;case "IS NULL":d.key=c.pop(),a=r(d.key+" IS NOT NULL NOT",b)}c.push(a)})}catch(E){k(E+"processReversePolishNotation",20)}return c.pop()}function l(a,
b){function d(a,b){return function(d,c){try{var f=0,q=r(c.cond,b);if(void 0!==q)if("boolean"===typeof q){if(void 0===c.incr||a)c.incr=0;q&&(c.incr+=1);f=c.coef*c.incr}else f=c.coef*parseFloat(b[q])||0;else f=c.coef||0;return d+f}catch(Y){return k(Y+"setScore: scoreReducer: no score increment",20),d}}}try{var c=a.events.reduce(d(void 0===a.ts||b.rtgsession_ts-a.ts>86400*a.ttl,b),0);a.score=Math.floor(1E3/(1+Math.exp(-c)));a.ts=b.rtgsession_ts}catch(y){k(y+"setScore: could not compute score",20)}return a}
function J(a){var b={isValid:!0,msg:""};try{b=h.models.reduce(function(a,c){try{c.events.forEach(function(a){if(""===a.coef||void 0===a.coef)b.isValid=!1,b.msg+=b.msg?"|coef":"coef"})}catch(y){k(y+b.msg+"+checkError+function+failed&engagement",20)}return a},b)}catch(A){k(A+b.msg+"+checkError+function+failed&engagement",20)}return b}var h=this;h.models=[];var p=function(a){try{var b=a.filter(function(a){return"default"!==a.id});if(0<b.length)return encodeURIComponent(JSON.stringify(b))}catch(A){k(A+
"stringifyModels",20)}return""},n=function(){return p(h.models)};(function(b,d){try{a:{try{if(b&&0<b.length){var f=JSON.parse(decodeURIComponent(b));break a}}catch(y){k(y+"parseModels",20)}f=[]}h.models=f;0===h.models.length&&(h.models=c());var g=J(h.models);g.isValid?h.models=h.models.map(function(a){return l(a,d)}):(k(g.msg+"init+function+failed+model+not+valid+&engagement=20"),h.models=a(d))}catch(y){k(y+"+init+function+failed&engagement",20),h.models=a(d)}})(b,d);h.lexer=g;h.evaluateExpression=
m;h.processReversePolishNotation=r;h.getScores=function(a){function b(a,b,c){return a+"&"+b}function c(a){return void 0!==a?"rtg"+a.id+"_score="+encodeURIComponent(a.score)+"&rtg"+a.id+"_version="+encodeURIComponent(a.version):""}try{if(0<h.models.length)return h.models.map(c).reduce(b);k("+getScores+function+empty+models&engagement",20)}catch(E){k(E+"getScore",20)}return""};h.getScoresForTagContainer=function(){try{if(0<h.models.length)return h.models.reduce(function(a,b){a.push(["rtg"+b.id+"_score",
[b.score]]);a.push(["rtg"+b.id+"_version",[b.version]]);return a},[])}catch(W){k(W+"getScoresForTagContainer",20)}return[]};h.getEncodedModels=n;h.updateEv=function(a){function b(a,b){a["rtg"+b.id+"_score"]=b.score;a["rtg"+b.id+"_version"]=b.version;return a}try{0<h.models.length&&(a=h.models.reduce(b,a))}catch(A){k(A+"+updateEv fail",20)}return a};h.writeNewModelsToCookie=function(a){try{for(var b=[],c=h.models.reduce(function(a,b){a[b.id]=b;return a},{}),d=0;d<a.length;d+=1){var g=a[d];if(void 0!==
c[g.id]){for(var m=0;m<g.events.length;m+=1)c[g.id].events[m].coef=g.events[m].coef;c[g.id].version=g.version;b.push(c[g.id])}else b.push(a[d])}h.models=b;B("__trossion",f._session.getValue()+"_"+n(),395)}catch(F){k(F+"+writeNewModelsToCookie fail",20)}};return h}function N(b){try{var d=Array.prototype.slice.call(arguments,0);b=d.shift();switch(b){case "init":f.tagid||(f.tagid=d[0],O());break;case "session_ttl":d[0]&&(f.session_ttl=d[0]);break;case "tag":u=[];var c=d[0];d=[];for(var a in c)if(c.hasOwnProperty(a))if("rtg"===
a.substring(0,3))u.push(z(a,[c[a]])),d.push([a,[c[a]]]);else if("exclusion"===a)u.push("exclusion=1"),d.push([a,["1"]]);else if("m5e"===a||"sha256"===a||"email"===a)u.push(z(a,[c[a]])),d.push([a,[c[a]]]);P(u,d,c)}}catch(m){k(m,14)}}function P(b,d,c){try{d.push(["r1",[l]]);c.r1=l;d.push(["vruid",[v]]);c.vruid=v;if(null!==t&&""!==t){try{var a=encodeURIComponent(t)}catch(K){a=escape(t)}d.push(["u",[a]]);c.u=a}var m=f.etag+"_"+(f.version?f.version:"0");d.push(["v",[m]]);c.v=m;var g=C("__trossion").split("_"),
r=g.splice(7);f._session=new I(g,f.uid,f.session_ttl);f._session.updateEv(c);d=d.concat(f._session.getSessionForTagContainer());f._en=new L(r.join("_"),c);f._en.updateEv(c);b.push("trossion="+f._session.getEncodedValue());if(!f.tagid)throw"tagid is missing";b.push(f._en.getScores());d=d.concat(f._en.getScoresForTagContainer());Q(b);B("__trossion",f._session.getValue()+"_"+f._en.getEncodedModels(),395);f.segq.queue?f.segq.tag?f.segq.tag.apply(f.segq,c):f.segq.queue.push(c):f.segq.push.apply(f.segq,
d)}catch(K){k(K,3)}}function R(){if(!f.unqueue_called){try{if(f.queue)for(;f.queue.length;){var b=f.queue.shift();N.apply(this,b)}else u=Array.prototype.splice.call(f,0),f.push()}catch(d){k(d,7)}f.unqueue_called=!0}}function S(b){try{b.queue&&(b=b.queue);for(var d=0;d<b.length;d++)if(b[d]&&b[d][0]&&("tagid"===b[d][0]||"init"===b[d][0])&&""!==b[d][1]){var c=b[d][1].split("-");if(2!=c.length)throw"Tagid is misstructured"+encodeURIComponent(b[d][1]);if(!c[1]||!H(c[1]))throw"Tag hash is invalid"+encodeURIComponent(c[1]);
if(!c[0]||!w(c[0]))throw"Tagid is invalid"+encodeURIComponent(c[0]);if(0!==c[0].indexOf("6"))throw"Tagid identifier is not valid  "+encodeURIComponent(c[0]);return b[d][1]}throw"Tagid is missing";}catch(a){k(a,13)}}x._troqck=x._troqck||0;if(!x._troqck){var T=!1,l="",t=n;n=t.hostname.split(".").reverse();f.etag=V;var U=2<n.length&&3>=n[1].length&&2>=n[0].length?"."+n[2]+"."+n[1]+"."+n[0]:"."+n[1]+"."+n[0];x!==top&&p.referrer&&""!==p.referrer&&(t=p.referrer);var z=function(b,d){for(var c="",a=0;a<d.length;a++)0<
a&&(c+="|"),c+=d[a];try{c=b+"="+encodeURIComponent(c)}catch(m){c=b+"="+escape(c)}return c};f.urlize=z;var C=function(b){var d,c=p.cookie.split(";");for(d=0;d<c.length;d++){var a=c[d].substr(0,c[d].indexOf("="));var f=c[d].substr(c[d].indexOf("=")+1);a=a.replace(/^\s+|\s+$/g,"");if(a===b)try{return decodeURIComponent(f)}catch(g){return unescape(f)}}return""};f.getCookie=C;var B=function(b,d,c){var a=new Date;a.setDate(a.getDate()+c);var f=d;try{d=encodeURIComponent(d)}catch(M){d=escape(d)}var g=d;
c=null===c?"":"; expires="+a.toUTCString();g=g+c+("; domain="+U+"; path=/");p.cookie=b+"="+g;try{var r=C(b);if(""===r||r!=f){var l=x.location.hostname;if(1===l.split(".").length)p.cookie=b+"="+d+c+"; path=/";else{var n=l.split(".");n.shift();var h="."+n.join(".");p.cookie=b+"="+d+c+"; path=/; domain="+h;r=C(b);if(""===r||r!=f)p.cookie=b+"="+d+c+"; path=/; domain="+U}}}catch(M){k(M,1)}};f.setCookie=B;f.isNumeric=w;f.isValidRUID=D;f.isMD5Valid=H;f.Session=I;f.Engagement=L;var Q=function(b,d){try{if(null==
f.tagid||""===f.tagid)throw"tagid is missing";var c="tagid="+f.tagid+"&";c+="r1="+l+"&";for(c+="vruid="+v+"&";0<b.length;)c+=b.shift()+"&";if(null!==t&&""!==t){c+="u=";try{c+=encodeURIComponent(t)}catch(a){c+=escape(t)}c+="&"}c+="v="+f.etag+"_";c+=(f.version?f.version:"0")+"&";c+="rnd="+Math.round(2E9*Math.random());b="https://"+(d||"mmtro.com")+"/p?"+c;(new Image(1,1)).src=b}catch(a){k(a,3)}};f.troPix=Q;f.push=function(){try{for(var b=0;b<arguments.length;b++)u.push(arguments[b])}catch(h){k(h,4)}b=
[];for(var d=[],c=[],a={};0<u.length;)try{var m=u.shift(),g=m.shift();if(!g)throw"empty array in taggage";g=g.toLowerCase();var l=m,n=!1;if("tagid"===g)f.tagid||(f.tagid=S([[g,l[0]]])),n=!0;else if("rtg"===g.substring(0,3)||-1!==g.indexOf("_")){0===g.indexOf("_")&&(g=g.substring(1,g.length));var p=z(g,l);d.push(p);c.push([g,l]);a[g]=p.split("=")[1]}else"exclusion"===g?(d.push("exclusion=1"),c.push([g,["1"]]),a.exclusion="1"):"m5e"===g||"sha256"===g||"email"===g?(p=z(g,l),d.push(p),c.push([g,l]),a[g]=
p.split("=")[1]):b.push(z(g,l))}catch(h){k(h,5)}0<b.length&&k("wrong params in taggage "+b.join("&"),12);try{0<d.length||n?P(d,c,a):k("p is empty",16)}catch(h){k(h,6)}};f.callTro=N;f.unqueue=R;var G=function(b){var d=p.createElement("script");d.type="text/javascript";d.async=!0;d.src=b;b=p.getElementsByTagName("script")[0];b.parentNode.insertBefore(d,b)};f.createScript=G;f.jarSyncMMTRO=function(b){try{B("__troRUID",b,395),l=f.uid=b}catch(d){k(d,10)}};var k=function(b,d){b=b.message||b;b=encodeURIComponent(b.replace(/ /g,
"_"));b="https://err.mmtro.com/error?f=tro.js&u="+encodeURIComponent(x.location.href)+"&message="+b+"&try="+d+"&v="+f.etag+"_"+(f.version?f.version:"0");(new Image(1,1)).src=b},O=function(){if(null!=f.tagid&&""!=f.tagid){if("00000000-0000-0000-0000-000000000000"!==l)try{G("https://cdn.mmtro.com/seg/"+f.tagid.split("-")[0]+".js")}catch(b){k(b,8)}G("https://mmtro.com/trojs/"+f.tagid+"/"+l+"/"+v+"/exec.js")}};try{var u=[];f.segq=f.segq||[];if(null==v||""==v||!D(v))throw"vruid is invalid";l=C("__troRUID");
D(l)||(l&&k("ruid1 not valid: "+encodeURIComponent(l),18),T=!0,l=v);f.uid=l;f.session_ttl=1800;f.tagid=S(f);R();T&&B("__troRUID",l,395);O()}catch(b){k(b,11)}x._troqck=1}})
(window, document, location, _troq, "52b44cfc-5129-449b-804c-d398de909ed8", "394b3efd185fb03f78cb63ce");